{"name": "test_get_random_dog", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('self', <SubRequest 'dog_api' for <Function test_get_random_dog>>)", "trace": "file C:\\Users\\refer\\OneDrive\\Рабочий стол\\test_dog_api_with_allure\\test_dog_api_with_allure\\tests\\test_dog_api.py, line 4\n  @allure.feature('Random dog')\n  @allure.story('Получение фото случайной собаки и вложенные друг в друга шаги')\n  def test_get_random_dog(dog_api):\nfile C:\\Users\\refer\\OneDrive\\Рабочий стол\\test_dog_api_with_allure\\test_dog_api_with_allure\\conftest.py, line 20\n  @pytest.fixture\n  def dog_api(self):\nE       fixture 'self' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, dog_api, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\refer\\OneDrive\\Рабочий стол\\test_dog_api_with_allure\\test_dog_api_with_allure\\conftest.py:20"}, "start": 1680020347531, "stop": 1680020347531, "uuid": "e6add651-a14e-42f4-b963-fd9b6b8370d0", "historyId": "81d09031a338a71922c560f3b239c182", "testCaseId": "0c67f1be437fe039626580e0d3f9c1a3", "fullName": "tests.test_dog_api#test_get_random_dog", "labels": [{"name": "feature", "value": "Random dog"}, {"name": "story", "value": "Получение фото случайной собаки и вложенные друг в друга шаги"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_dog_api"}, {"name": "host", "value": "Ushakov"}, {"name": "thread", "value": "8444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_dog_api"}]}